const data = {
    ar: {
        ConfirmDelete: "تاكيد عملية الحذف",
        SuccessfullyDeleted: "تم الحذف بنجاح",
        AddedSuccessfully: "تمت الاضافه بنجاح",
        UpdatedSuccessfully: "تمت التحديث بنجاح",
        GroupNameIsRequired: "يرجي اضافة اسم المجموعه اولا",
        PleaseSpecifyPermissions: "يرجي تحديد صلاحيات اولا",
        PleaseEnterAUsername: "يرجي ادخال اسم مستخدم ",
        PleaseEnterTheFullName: "يرجي ادخال  الاسم بالكامل",
        PleaseEnterYourPassword: "يرجي ادخال   كلمه المرور",
        PasswordWeakPleaseEnterAtLeast5LettersOrNumbers: "كلمه مرور ضعيفة ,, يرجي ادخال علي الاقل 5 حروف او ارقام",
        PasswordsDoNotMatch: "كلمة المرور غير مطابقة",
        PleaseEnterAnEmailAddress: "يرجي ادخال عنوان بريد الكتروني",
        PleaseEnterTheDepartment: "يرجي ادخال القسم",
        PleaseEnterTheDivision: "يرجي ادخال الشعبة",
        CanNotAddMoreThan4Levels: "لا يمكن اضافة اكثر من 4 مستويات",
        PleaseEnterName: "يرجى ادخال الاسم",
        PleaseEnterMobile: "يرجى ادخال رقم الهاتف",
        PleaseEnterReason: "يرجى ادخال السبب",
        PleaseEnterNationID: "يرجى ادخال الرقم القومى",
        PleaseEnterDate: "يرجى ادخال التاريخ",
        PleaseEnterTime: "يرجى ادخال الوقت",
        PleaseEnterCallerName: "يرجى ادخال اسم المتصل",
        PleaseEnterCallerMobile: "يرجى ادخال رقم المتصل",
        PleaseEnterNotes: "يرجى ادخال الملاحظات",
        PleaseEnterDateFrom: "يرجى ادخال الفترة من",
        PleaseEnterDateTo: "يرجى ادخال الفترة الى",
        ConfirmVisitEnd: "تاكيد انهاء الزيارة ؟!!",
        EndVisitSuccess: "تم انهاء الزيارة",
        PleaseEnterGateEntriesItems: "يرجى ادخال مدخلات البوابة",
        SetdefaultNation: "هل ترغب فى تعينها جنسية افتراضية",
        PleaseEnterNationality: "يرجى ادخال اسم الجنسية",
        PleaseEnterNationalityEn: " يرجى ادخال اسم الجنسية بالانجليزى",
        WriteHere: "اكتب هنا ...",
        NumberOfTreeLevelsCalculationsIsRequired: "يرجي ادخال عدد مستويات شجرة الحسابات",
        StagesOfTreeAccountsIsRequired: "يرجي ادخال عدد مراحل شجرة الحسابات",

        MaximumValuesForLevelsAreOnly10Levels: "اقصي قيمة للمستويات هي 10 مستويات فقط",
        DigitSystemIsRequired: "يرجي اضافة نظام الـ Digit المتبع",

        PleaseEnterBookName: "يرجي ادخال  اسم الكتاب",
        PleaseEnterBookNumber: "يرجي ادخال  رقم الكتاب",
        PleaseEnterBookParcode: "يرجي ادخال  الباركود",
        PleaseEnterBookPlace: "يرجي ادخال  مكان الكتاب",
        PleaseEnterPublisher: "يرجي ادخال  اسم الناشر",
        PleaseEnterAboutBook: "يرجي ادخال  اسم المؤلف",
        FileUploadSuccessfully: "تمت اضافة الملف بنجاح",
        PleaseEnterPath: " PDF يرجى ادخال ",
        someThingWentWrong: "حصل خطأ ما",
        saved: "تم الحفظ",
        deleted:"تم الحذف",
        PleaseAddTheBeginningOfTheYear: "يرجي ادخال بداية السنة المالية",
        PleaseAddTheEndOfTheYear: "يرجي ادخال نهاية السنة المالية",
        committeeNameOrNumberIsRepeated: "اسم او رقم اللجنة تم ادخالهم مسبقا",
        makeSureToChoseAcontrolAdepartmentAndAbranche: "تأكد من اختيار كنترول و قسم ومدرسه",
        text: "نصى",
        number: "رقمي",
        check: "صح او خطأ",
        bankNameArabic_Required: "يرجي اضافه اسم البنك باللغه العربيه",
        bankNameEnglish_Required: "يرجي اضافه اسم البنك باللغه الانجليزيه",
        bankAccountNumber_Required: "يرجي اضافه رقم الحساب البنكي",
        accountNumber_Required: " يرجي اضافه رقم الحساب الخاص بشجره الحسابات",
        accountOwner_Required: " يرجي اضافه اسم صاحب الحساب",
        address_Required: "يرجي اضافه العنوان",
        BankIsRequired:"يرجي اختيار بنك",
        safeNameArabic_Required: "يرجي اضافه اسم الخزينه باللغه العربيه",
        safeNameEnglish_Required: "يرجي اضافه اسم الخزينه باللغه العربيه",
        cashierIsSafe_Required: "يرجي اضافه اسم امين صندوق الخزينه ",
        Branches: "الفروع",
        branche_Required: "يرجي ربط الحساب بفرع واحد علي الاقل",
        PleaseAddTheNameOfTheBook: "يرجي اضافه اسم الدفتر",
        PleaseAddAStartDate: "يرجي اضافه بدايه الفتره",
        PleaseAddAEndtDate: "يرجي اضافه نهايه الفتره",
        branchIsRequired: "يرجي اختيار فرع",
        financialYearIsRequired: "يرجي اختيار سنه ماليه",
        currencyIsRequired: "يرجي اختيار عمله",
        PaperReceiptIsRequired:"يرجي اختيار اسم الدفتر",
        historyOfTheMovementIsRequired:"يرجي اختيار تاريخ السند",
        PaperReceiptNumberIsRequired: "يرجي اضافه رقم الايصال الورقي",
        DateOfReceiptIsRequired: "يرجي اضافه تاريخ الايصال ",
        TypeOfCashReceiptsIsRequired: "يرجي اختيار نوع الحساب",
        AccountIsRequired: "يرجي اختيار حساب",
        supplementIsRequired:"يرجي اختيار الحساب المكمل",
        PaperReceiptNumber:"رقم الايصال خارج الفتره المححده",
        AccountNumberReceiptIsRequired: "يرجي اختيار نوع حساب  القبض",
        PleaseSelectAtLeastOneAccountToCompleteTheProcess:"يرجي اختيار علي الاقل حساب واحد فقط لاكمال العمليه",
        PleaseFillInAllTheDataInTheTableFirst:"يرجي ملئ جميع البيانات في الجدول اولا",
        CheckNumberIsRequired: "يرجي اضافه رقم الشيك",
        DueDateIsRequired: "يرجي اضافه تاريخ الاستحقاق",
        InvalidDateTimeFormatting:"يرجي اضافه التاريخ بشكل صحيح",
        PleaseAddAEndtDate: "يرجي اضافه نهايه الفتره",
        PleaseAddAEndtDate: "يرجي اضافه نهايه الفتره",
        namerepeated: "الاسم مكرر",
        coderepeated: "رقم الكود مكرر",
        nationalidRepeated:"الرقم القومى مكرر",



         PleaseEnterBookdivisionName: "يرجي ادخال اسم الشعبه",
        PleaseEnterbranchName: "يرجي ادخال اسم الفرع",
        Cannotdelete: "لا يمكن الحذف",
        
        
        PasswordWeakPleaseEnterAtLeast5LettersOrNumbers: "كلمه مرور ضعيفة ,, يرجي ادخال علي الاقل 5 حروف او ارقام",
        PasswordsDoNotMatch: "كلمة المرور غير مطابقة",
        PleaseEnterAnEmailAddress: "يرجي ادخال عنوان بريد الكتروني",
        PleaseEnterTheDepartment: "يرجي ادخال القسم",
        Department: "القسم",
        TheDivision: " الشعبة",
        PleaseEnternewcount: "يرجي ادخال رصيد الكتب الجديد",
        PleaseEnterTheDivision: "يرجي ادخال الشعبة",
        CanNotAddMoreThan4Levels: "لا يمكن اضافة اكثر من 4 مستويات",
        PleaseEnterName: "يرجى ادخال الاسم",
        PleaseEnterstudentName: "  يرجى ادخال الاسم الطالب ",
        studentName: "  الاسم الطالب ",
        PleaseEnterMobile: "يرجى ادخال رقم الهاتف",
        PleaseEnterReason: "يرجى ادخال السبب",
        PleaseEnterNationID: "يرجى ادخال الرقم القومى",
        PleaseEnterDate: "يرجى ادخال التاريخ",
        PleaseEnterTime: "يرجى ادخال الوقت",
        PleaseEnterCallerName: "يرجى ادخال اسم المتصل",
        PleaseEnterCallerMobile: "يرجى ادخال رقم المتصل",
        PleaseEnterNotes: "يرجى ادخال الملاحظات",
        PleaseEnterDateFrom: "يرجى ادخال الفترة من",
        PleaseEnterDateTo: "يرجى ادخال الفترة الى",
        ConfirmVisitEnd: "تاكيد انهاء الزيارة ؟!!",
        EndVisitSuccess: "تم انهاء الزيارة",
        PleaseEnterGateEntriesItems: "يرجى ادخال مدخلات البوابة",
        SetdefaultNation: "هل ترغب فى تعينها جنسية افتراضية",
        PleaseEnterNationality: "يرجى ادخال اسم الجنسية",
        PleaseEnterNationalityEn: " يرجى ادخال اسم الجنسية بالانجليزى",
        WriteHere: "اكتب هنا ...",
        NumberOfTreeLevelsCalculationsIsRequired: "يرجي ادخال عدد مستويات شجرة الحسابات",
        StagesOfTreeAccountsIsRequired: "يرجي ادخال عدد مراحل شجرة الحسابات",
        branches: "الفرع",
        MaximumValuesForLevelsAreOnly10Levels: "اقصي قيمة للمستويات هي 10 مستويات فقط",
       
        PleaseEnterAnotes: "يرجي ادخال الملاحظات",
        PleaseEnterBookName: "يرجي ادخال  اسم الكتاب",
        BookName: "اسم الكتاب",
        AuthorName: "اسم المؤلف",
        PublicNum: " الرقم العام",
        PrivateNum: "الرقم الخاص",
        Publisher: "الناشر",
        InPeriod: "خلال فتره",
        PleaseEnterBookNumber: "يرجي ادخال  رقم الكتاب",
        PleaseEnterBookParcode: "يرجي ادخال  الباركود",
        PleaseEnterBookPlace: "يرجي ادخال  مكان الكتاب",
        PleaseEnterPublisher: "يرجي ادخال  اسم الناشر",
        PleaseEnterAboutBook: "يرجي ادخال  اسم المؤلف",
    
        PleaseEnterPath: " PDF يرجى ادخال ",
        someThingWentWrong: "حصل خطأ ما",
        saved: "تم الحفظ",
        deleted: "تم الحذف",
        PleaseAddTheBeginningOfTheYear: "يرجي ادخال بداية السنة المالية",
        PleaseAddTheEndOfTheYear: "يرجي ادخال نهاية السنة المالية",
        committeeNameOrNumberIsRepeated: "اسم او رقم اللجنة تم ادخالهم مسبقا",
        makeSureToChoseAcontrolAdepartmentAndAbranche: "تأكد من اختيار كنترول و قسم ومدرسه",
        text: "نصى",
        number: "رقمي",
        check: "صح او خطأ",
        deleteConfimation: "متأكد من حذف السجل؟",
        commonData: "بيانات عامة",
        birthData: "بيانات الميلاد",
        addressData: "بيانات العنوان",
        medicalStateData: "بيانات الحالة الصحية",
        date: "تاريخ",
        check: "اختر",
        PleaseEnterinfiractionrate: "يرجي ادخال تصنيف المخالفه",
        PleaseEnterinfiractionname: "يرجي ادخال المخالفه",
        Addedinfrationratingbefor: "تمت  اضافه هذه المخالفه  من قبل",
        Duplicatename: "اسم مكرر",
        PleaseEnterDestructionABooknumber: "يرجي ادخال عدد الكتب المهلكه",
        Allcopiesofthebookareborrowed: "كل نسخ الكتاب مستعاره",
        Thestudentborrowedthebookbefore: "الطالب قام باستعاره الكتاب من قبل",
        nobook: "عدد الكتب غير كافي",
        show: "عرض",
        accountNameRepeated: "اسم الحساب مكرر",
        noStudentsAccountSet: "من فضلك قم بضبط اعدادت حساب الطلاب",
        PleaseAddTheQuedNumber:'يرجي اضافه رقم القيد',
        PleaseAddAnotherComplementaryAccount:"يرجي اضافه حساب مكمل اخر",
        show: "عرض"
    },
    en: {
        PleaseAddAnotherComplementaryAccount: "Please add another complementary account",

        supplementIsRequired: "Please choose the supplement account",
        PleaseAddTheQuedNumber:'Please Add The Qued Number',
        AccountIsRequired:"Account Is Required",
        PaperReceiptNumber:"Receipt number outside the specified period",
        InvalidDateTimeFormatting:"Invalid Date Time Formatting",
        BankIsRequired:"Bank Is Required",
        DueDateIsRequired:"Due Date Is Required",
        CheckNumberIsRequired:"Check Number Is Required",
        PleaseFillInAllTheDataInTheTableFirst:"Please Fill In All The Data In The Table First",
        PleaseSelectAtLeastOneAccountToCompleteTheProcess: "Please select at least one account to complete the process",
        AccountNumberReceiptIsRequired:"Account Number Receipt Is Required",
        TypeOfCashReceiptsIsRequired:"Type Of Cash Receipts IsRequired",
        DateOfReceiptIsRequired:"Date Of Receipt Is Required",
        PaperReceiptNumberIsRequired:"Paper Receipt Number Is Required",
        PaperReceiptIsRequired: "Paper Receipt Is Required",
        ConfirmDelete: "Confirm Delete Operation",
   
       
        AddedSuccessfully:"Added Successfully",
        
        PasswordWeakPleaseEnterAtLeast5LettersOrNumbers: "Password Weak << Please Enter At Least 5 Letters Or Numbers",
        PasswordsDoNotMatch: "Passwords Donot Match",
        PleaseEnterAnEmailAddress: "Please Enter An Email Address",
        PleaseEnterTheDepartment: "Please Enter The Department",
        PleaseEnterTheDivision: "Please Enter The Division",
        CanNotAddMoreThan4Levels: "Can Not Add More Than 4 Levels",
        PleaseEnterName: "The Name Is Required !!",
        PleaseEnterMobile: "The Mobile Is Required !!",
        PleaseEnterReason: "The Reason Is Required !!",
        PleaseEnterNationID: "The NationID Is Required !!",
        PleaseEnterDate: "The Date Is Required !!",
        PleaseEnterTime: "The Time Is Required !!",
        PleaseEnterCallerName: "The Caller Name Is Required !!",
        PleaseEnterCallerMobile: "The Caller Mobile Is Required !!",
        PleaseEnterNotes: "The Notes Is Required !!",
        PleaseEnterDateTo: "The Date To Is Required !!",
        PleaseEnterDateFrom: "The Date From Is Required !!",
        ConfirmVisitEnd: "Confirm End Visit?",
        EndVisitSuccess: "Success End Visit",
        PleaseEnterGateEntriesItems: "The Gate Entries Items Is Required !!",
        SetdefaultNation: "Set Default Nationality?",
        PleaseEnterNationality: "The Nationality Name Is Required",
        PleaseEnterNationalityEn: "The Nationality English Name Is Required",
        WriteHere: "Write Here ...",
        NumberOfTreeLevelsCalculationsIsRequired: "Number Of Tree Levels Calculations Is Required",
        StagesOfTreeAccountsIsRequired: "Number Of Tree Stages  Calculations Is Required",
        MaximumValuesForLevelsAreOnly5Levels: "Maximum Values For Levels Are Only 10 Levels",
        DigitSystemIsRequired: "Digit System Is Required",

        PleaseEnterBookName: "The Name Is Required !!",
        PleaseEnterBookNumber: "The Number Is Required !!",
        PleaseEnterBookParcode: "The Parcode Is Required !!",
        PleaseEnterBookPlace: "The Place Is Required !!",
        PleaseEnterPublisher: "The Publisher Is Required !!",
        branchIsRequired: "The Branch Is Required !!",
        financialYearIsRequired: "The Financial Year Is Required !!",
        historyOfTheMovementIsRequired: "The History Of The Movement Is Required !!",

        currencyIsRequired: "The Currency Is Required !!",
        PleaseEnterAboutBook: "The About Book Is Required !!",
        FileUploadSuccessfully: "File Upload Successfully",
        PleaseEnterPath: "The File Is Required !!",
        someThingWentWrong: "Some Thing Went Wrong",
        committeeNameOrNumberIsRepeated: "Committee Name Or Number Is Repeated",
        saved: "saved",
        deleted:"deleted",
        PleaseAddTheBeginningOfTheYear: "Please Add The Beginning Of The Year",
        PleaseAddTheEndOfTheYear: "Please Add The End Of The Year",
        makeSureToChoseAcontrolAdepartmentAndAbranche: "make Sure To Chose A control A department And A branche",
        text: "text",
        number: "number",
        check: "check",
        bankNameArabic_Required: "Please add the name of the bank in Arabic",
        bankNameEnglish_Required: "Please add the name of the bank in English",
        bankAccountNumber_Required: "Please add bank account number",
        accountNumber_Required: "Please add the account number for the accounts tree",
        accountOwner_Required: "Please add the account owner name",
        address_Required: "Please add the address",

        safeNameArabic_Required: "Please add the name of the safe in Arabic",
        safeNameEnglish_Required: "Please add the name of the safe in English",
        cashierIsSafe_Required: "Please add the  cashier's safe Name",
        
        branche_Required: "Please link the account to at least one branch",

        PleaseAddTheNameOfTheBook: "Please add the name of the book",
        PleaseAddAStartDate: "please add the beginning of the period",
        PleaseAddAEndtDate: "please add the end of the period",
        studentName: "student Name",
        branches: "branches",
        TheDivision: "The Division",
        Department: "Department",
        PleaseEnterDestructionABooknumber: "Please Enter Destruction Book number",
        Thestudentborrowedthebookbefore: "The student borrowed the book before",
        Allcopiesofthebookareborrowed: "All copies of the book are borrowed",
        
        SuccessfullyDeleted: "Successfully Deleted",
       
        UpdatedSuccessfully: "Updated Successfully",
        GroupNameIsRequired: "The Group Name Is Required !!",
        PleaseSpecifyPermissions: "Please specify permissions!!",
        PleaseEnterAUsername: "Please Enter A Username",
        PleaseEnterTheFullName: "Please Enter The Full Name",
        PleaseEnterYourPassword: "Please Enter Your Password",
        PasswordWeakPleaseEnterAtLeast5LettersOrNumbers: "Password Weak << Please Enter At Least 5 Letters Or Numbers",
        PasswordsDoNotMatch: "Passwords Donot Match",
        PleaseEnterAnEmailAddress: "Please Enter An Email Address",
        PleaseEnterTheDepartment: "Please Enter The Department",
        PleaseEnterTheDivision: "Please Enter The Division",
        CanNotAddMoreThan4Levels: "Can Not Add More Than 4 Levels",
        PleaseEnterName: "The Name Is Required !!",
        PleaseEnterMobile: "The Mobile Is Required !!",
        PleaseEnterReason: "The Reason Is Required !!",
        PleaseEnterNationID: "The NationID Is Required !!",
        PleaseEnterDate: "The Date Is Required !!",
        PleaseEnterTime: "The Time Is Required !!",
        PleaseEnterCallerName: "The Caller Name Is Required !!",
        PleaseEnterCallerMobile: "The Caller Mobile Is Required !!",
        PleaseEnterNotes: "The Notes Is Required !!",
        PleaseEnterDateTo: "The Date To Is Required !!",
        PleaseEnterDateFrom: "The Date From Is Required !!",
        ConfirmVisitEnd: "Confirm End Visit?",
        EndVisitSuccess: "Success End Visit",
        PleaseEnterGateEntriesItems: "The Gate Entries Items Is Required !!",
        SetdefaultNation: "Set Default Nationality?",
        PleaseEnterNationality: "The Nationality Name Is Required",
        PleaseEnterNationalityEn: "The Nationality English Name Is Required",
        WriteHere: "Write Here ...",
        NumberOfTreeLevelsCalculationsIsRequired: "Number Of Tree Levels Calculations Is Required",
        StagesOfTreeAccountsIsRequired: "Number Of Tree Stages  Calculations Is Required",
        MaximumValuesForLevelsAreOnly5Levels: "Maximum Values For Levels Are Only 10 Levels",
       
     
        BookName: "Book Name",
      
       
      
        PleaseEnterBookdivisionName: "Please Enter Book division Name",
        deleteConfimation: "do you want to delete?",
        commonData: "common Data",
        birthData: "birth Data",
        addressData: "address Data",
        medicalStateData: "medical State Data",
        date: "date",
        check: "check",
        show: "show",
        Cannotdelete: "Cannot delete",
        PleaseEnterbranchName: "Please Enter branch Name",
        PleaseEnterstudentName: "Please Enter student Name",
        PleaseEnterAnotes: "Please Enter Anotes",
        PleaseEnterinfiractionrate: "Please Enter infiraction rate",
        PleaseEnterinfiractionname: "Please Enter infiraction name",
        Addedinfrationratingbefor: " infration rating added befor",
        Duplicatename: "Duplicate name",
        nobook: "book number not enough",
        AuthorName: "AuthorName",
        PublicNum: " PublicNum",
        PrivateNum: "PrivateNum",
        Publisher: "Publisher",
        InPeriod: "InPeriod",
        PleaseEnternewcount: "Please Enter new count",

        PleaseAddAEndtDate:"please add the end of the period"  ,
        namerepeated: "name repeated",
        coderepeated: "code repeated",
        nationalidRepeated: "nationalid Repeated",
        accountNameRepeated: "account name repeated",
           noStudentsAccountSet:"please set a studnet Main account"
    }
};
function getCookieValue(a) {
    var b = document.cookie.match('(^|[^;]+)\\s*' + a + '\\s*=\\s*([^;]+)');
    return b ? b.pop() : '';
}
angular.module("LmsApp_Services").factory("CulutrServices", () => {



    let getToken = (key) => {
        let lang = getCookieValue('Usre_Culture') === 'ar-EG' ? 'ar' : 'en';

        return data[lang][key];
    };
    return {
        GetToken: getToken
    };
});